# Generated by Django 4.2.25 on 2025-12-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_TMR', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['start_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='roadmap',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='終了日'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='content',
            field=models.TextField(help_text='詳細な内容', verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
