# Generated by Django 4.2.25 on 2026-01-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_TMR', '0002_alter_roadmap_options_roadmap_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='decision',
            field=models.CharField(blank=True, max_length=200, verbose_name='内定先'),
        ),
        migrations.AddField(
            model_name='profile',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='卒業年度'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lab',
            field=models.CharField(blank=True, max_length=200, verbose_name='研究室'),
        ),
    ]
