# Generated by Django 4.2.25 on 2026-01-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_TMR', '0003_profile_decision_profile_graduation_year_profile_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='research_field',
            field=models.CharField(blank=True, max_length=200, verbose_name='研究分野'),
        ),
    ]
