# Generated by Django 4.2.25 on 2025-12-15 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='実験名（タイトル）')),
                ('organizer_name', models.CharField(help_text='研究室名や氏名など', max_length=100, verbose_name='主催者名')),
                ('edit_password', models.CharField(help_text='4桁の数字を入力してください（例: 1234）', max_length=4, validators=[django.core.validators.RegexValidator(message='パスワードは4桁の数字で入力してください', regex='^\\d{4}$')], verbose_name='編集・削除用パスワード')),
                ('description', models.TextField(verbose_name='実験概要')),
                ('category', models.CharField(choices=[('psychology', '心理学'), ('medical', '医学'), ('engineering', '工学'), ('survey', 'アンケート'), ('other', 'その他')], default='other', max_length=50, verbose_name='カテゴリ')),
                ('application_url', models.URLField(help_text='Google Forms等のURLを入力してください', verbose_name='応募用URL')),
                ('schedule', models.DateTimeField(verbose_name='実施日時')),
                ('duration', models.CharField(help_text='例: 60分程度', max_length=100, verbose_name='所要時間')),
                ('location', models.CharField(help_text='例: ○○キャンパス 3号館201室', max_length=200, verbose_name='実施場所')),
                ('reward', models.CharField(help_text='例: 時給1140円', max_length=200, verbose_name='謝礼')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='応募条件')),
                ('capacity', models.IntegerField(default=1, help_text='例: 10', verbose_name='募集人数')),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '募集終了')], default='open', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '実験募集投稿',
                'verbose_name_plural': '実験募集投稿一覧',
            },
        ),
    ]
