# Generated by Django 4.2.25 on 2026-01-05 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_empiricism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentpost',
            name='schedule',
        ),
        migrations.AddField(
            model_name='experimentpost',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='募集終了日'),
        ),
        migrations.AddField(
            model_name='experimentpost',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='募集開始日'),
        ),
    ]
