# Generated by Django 4.2.25 on 2025-12-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_empiricism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentpost',
            name='category',
            field=models.CharField(choices=[('hukumura', '生体運動制御システム研究室（福村研）'), ('kitazaki', '視覚心理物理学研究室（北崎研）'), ('nakauti', '視覚認知情報学研究室（中内研）'), ('other', 'その他')], default='other', max_length=50, verbose_name='研究室'),
        ),
    ]
