# Generated by Django 4.2.25 on 2026-01-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_empiricism', '0002_remove_experimentpost_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='研究室名')),
            ],
            options={
                'verbose_name': '研究室',
                'verbose_name_plural': '研究室一覧',
            },
        ),
        migrations.RemoveField(
            model_name='experimentpost',
            name='category',
        ),
        migrations.AddField(
            model_name='experimentpost',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='team_empiricism.laboratory', verbose_name='研究室'),
        ),
    ]
