# Generated by Django 4.2.25 on 2025-11-03 05:55

from django.db import migrations

SQL_SEED = """
-- multi-row で2件を一括挿入
INSERT INTO team_terrace_member (first_name, last_name)
VALUES
  ('Taro', 'Yamada'),
  ('Hanako', 'Sato');
"""

SQL_ROLLBACK = """
DELETE FROM team_terrace_member
WHERE (first_name='Taro' AND last_name='Yamada')
   OR (first_name='Hanako' AND last_name='Sato');
"""


class Migration(migrations.Migration):
    dependencies = [
        ("team_terrace", "0001_initial"),
    ]
    operations = [
        migrations.RunSQL(
            sql=SQL_SEED,
            reverse_sql=SQL_ROLLBACK,
        ),
    ]
