# Generated by Django 4.2.25 on 2025-12-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_terrace", "0004_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadReply",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="team_terrace.chatmessage",
                    ),
                ),
            ],
        ),
    ]
