# Generated by Django 4.2.25 on 2025-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_terrace', '0006_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
