# Generated by Django 4.2.25 on 2025-12-15 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(unique=True)),
                ('url', models.TextField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'floor_table',
            },
        ),
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.TextField()),
                ('building_id', models.CharField(max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='team_USL.floortable')),
            ],
            options={
                'db_table': 'room_table',
                'indexes': [models.Index(fields=['building_id', 'room_number', 'is_deleted'], name='room_table_buildin_4c49c3_idx')],
            },
        ),
    ]
