# Generated by Django 4.2.25 on 2025-11-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField(help_text='フロア番号（例: 1, 2, 3）')),
                ('url', models.TextField(help_text='フロア画像のURL')),
            ],
            options={
                'db_table': 'floor_table',
                'verbose_name': 'フロア',
                'verbose_name_plural': 'フロア',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50, help_text='部屋番号')),
                ('building_id', models.IntegerField(help_text='棟ID')),
                ('x', models.FloatField(help_text='フロア画像上のX座標（0.0〜100.0の割合を想定）')),
                ('y', models.FloatField(help_text='フロア画像上のY座標（0.0〜100.0の割合を想定）')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('floor',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='rooms',
                     help_text='所属フロア',
                     to='team_USL.floor',
                 )
                ),
            ],
            options={
                'db_table': 'room_table',
                'verbose_name': '部屋',
                'verbose_name_plural': '部屋',
            },
        ),
    ]
