# Generated by Django 4.2.25 on 2025-12-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0002_room_search_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
