# Generated by Django 4.2.25 on 2025-12-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0002_floortable_roomtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtable',
            name='floor',
        ),
    ]
