# Generated by Django 4.2.25 on 2025-12-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0003_remove_roomtable_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floortable',
            name='floor',
            field=models.TextField(unique=True),
        ),
    ]
