# Generated by Django 4.2.25 on 2025-12-15 08:32
from django.db import migrations

SQL_SEED = """
-- floor_table: A-1/A-2/A-3 の画像URLを投入（重複時は無視）
INSERT OR IGNORE INTO floor_table (url, created_dt, updated_dt, floor) VALUES
  ('images/A-1.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'A-1'),
  ('images/A-2.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'A-2'),
  ('images/A-3.png', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'A-3');

-- room_table: サンプル部屋データ投入（重複時は無視）
INSERT OR IGNORE INTO room_table (room_number, building_id, x, y, created_dt, updated_dt, is_deleted) VALUES
  ('101', 'A', 0.0, 0.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
  ('201', 'A', 0.0, 0.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0),
  ('301', 'A', 0.0, 0.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
"""

SQL_ROLLBACK = """
-- 0005で入れたものだけ消す
DELETE FROM floor_table
WHERE floor IN ('A-1', 'A-2', 'A-3');

DELETE FROM room_table
WHERE building_id='A' AND room_number IN ('101', '201', '301');
"""

class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0004_alter_floortable_floor'),
    ]

    operations = [
        migrations.RunSQL(
            sql=SQL_SEED,
            reverse_sql=SQL_ROLLBACK,
        ),
    ]
