# Generated by Django 4.2.25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0006_insert_data_A'), # 直前のmigrationを指定
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingFloorRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.TextField(unique=True)), # 棟の名前 (ex. A, A1, B)
                ('min_floor', models.IntegerField()),           # 最低階
                ('max_floor', models.IntegerField()),           # 最高階
            ],
            options={
                'db_table': 'building_floor_range',
            },
        ),
    ]