# Generated by Django 4.2.25 on 2026-01-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_USL', '0008_insert_building_ranges'),
    ]

    operations = [
    ]
