# Generated by Django 4.2.25 on 2025-11-10 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_northcliff', '0001_initial'),
    ]

    operations = [
    ]
