# Generated by Django 4.2.25 on 2025-11-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_northcliff', '0002_teammembers_sql'),
        ('team_northcliff', '0003_seed_members_sql'),
    ]

    operations = [
    ]
