# Generated by Django 4.2.25 on 2025-11-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_northcliff', '0004_merge_0002_teammembers_sql_0003_seed_members_sql'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(choices=[('lib', '🏢 図書館'), ('hiba', '🍴 食堂（ひばり）'), ('kita', '🅿️ 北駐車場'), ('bus', '🚌 バス停'), ('gym', '🏋️ ジム')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='施設名')),
            ],
            options={
                'verbose_name': '施設',
                'verbose_name_plural': '施設',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ユーザー名')),
                ('points', models.IntegerField(default=10, verbose_name='保有ポイント')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('empty', '🟢 空いている'), ('moderate', '🟡 やや混雑'), ('crowded', '🔴 混雑')], max_length=20, verbose_name='混雑状況')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='team_northcliff.facility', verbose_name='施設')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='team_northcliff.user', verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now=True, verbose_name='閲覧日時')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='team_northcliff.facility', verbose_name='施設')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_accesses', to='team_northcliff.user', verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '施設閲覧履歴',
                'verbose_name_plural': '施設閲覧履歴',
                'unique_together': {('user', 'facility')},
            },
        ),
    ]
