# Generated by Django 5.0.6 on 2025-12-16 01:07

from django.db import migrations

def seed_location_data(apps, schema_editor):
    """
    Seed location data for existing Facilities and Users.
    """
    Facility = apps.get_model("team_northcliff", "Facility")
    User = apps.get_model("team_northcliff", "User")

    # Provided coordinates for facilities
    facility_locations = {
        "🍴 食堂（ひばり）": {"latitude": 34.700797551357624, "longitude": 137.40906746128755},
        "🅿️ 北駐車場": {"latitude": 34.7030802064815, "longitude": 137.40754813094193},
        "🏢 図書館": {"latitude": 34.70084228819001, "longitude": 137.41008130531003},
        #"☕️ カフェ": {"latitude": 34.700938, "longitude": 137.408937},
        "🚌 バス停": {"latitude": 34.700886, "longitude": 137.412739},
        "🏋️ ジム": {"latitude": 34.701172, "longitude": 137.406699},
    }

    for name, coords in facility_locations.items():
        Facility.objects.filter(name=name).update(latitude=coords["latitude"], longitude=coords["longitude"])

    # Provided coordinates for users
    user_locations = {
        "田中太郎": {"latitude": 34.70079, "longitude": 137.40906},  # Near 食堂
        "鈴木花子": {"latitude": 34.70308, "longitude": 137.40754},  # Near 北駐車場
        "佐藤次郎": {"latitude": 34.70084, "longitude": 137.41008},  # Near 図書館
        "高橋美咲": {"latitude": 34.70093, "longitude": 137.40893},  # Near カフェ
        "伊藤健太": {"latitude": 34.716437, "longitude": 137.405312}, # Far away
    }

    for name, coords in user_locations.items():
        User.objects.filter(name=name).update(latitude=coords["latitude"], longitude=coords["longitude"])


def reverse_location_data(apps, schema_editor):
    """
    Set location data back to None.
    """
    Facility = apps.get_model("team_northcliff", "Facility")
    User = apps.get_model("team_northcliff", "User")

    Facility.objects.update(latitude=None, longitude=None)
    User.objects.update(latitude=None, longitude=None)


class Migration(migrations.Migration):

    dependencies = [
        ('team_northcliff', '0007_facility_latitude_facility_longitude_user_latitude_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_location_data, reverse_location_data),
    ]