# Generated by Django 4.2.25 on 2025-12-08 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='通し番号')),
                ('title', models.CharField(max_length=300, verbose_name='論文題目')),
                ('author', models.CharField(max_length=300, verbose_name='論文著者')),
                ('booktitle', models.CharField(max_length=300, verbose_name='掲載誌名')),
                ('year', models.IntegerField(verbose_name='年')),
                ('doi', models.CharField(max_length=100, verbose_name='DOI')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('submitter', models.CharField(max_length=100, verbose_name='登録者')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='登録時刻')),
                ('keywords', models.CharField(blank=True, max_length=300, verbose_name='キーワード')),
                ('imp_overview', models.TextField(verbose_name='どんな論文か')),
                ('imp_comparison', models.TextField(verbose_name='先行研究との比較')),
                ('imp_idea', models.TextField(verbose_name='技術や手法の中心的アイデア')),
                ('imp_usefulness', models.TextField(verbose_name='有効性の検証方法と結果')),
                ('imp_discussion', models.TextField(verbose_name='議論（利点，欠点，制限）')),
                ('imp_relation', models.TextField(blank=True, verbose_name='自身の研究との関連性')),
                ('note', models.TextField(blank=True, verbose_name='その他')),
                ('paper_file', models.FileField(blank=True, upload_to='paper_files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='論文ファイル')),
                ('rc_slide', models.FileField(blank=True, upload_to='rc_slides/', validators=[django.core.validators.FileExtensionValidator(['ppt', 'pptx', 'pdf'])], verbose_name='輪講スライド')),
                ('paper_figure', models.FileField(blank=True, upload_to='paper_figures/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'pdf'])], verbose_name='画像ファイル')),
            ],
        ),
    ]
