# Generated by Django 4.2.25 on 2025-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('booktitle', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('doi', models.CharField(max_length=100)),
            ],
        ),
    ]
