# Generated by Django 4.2.25 on 2025-12-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_papers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Papers',
            new_name='Paper',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='authors',
            new_name='author',
        ),
    ]
