# Generated by Django 4.2.25 on 2025-12-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='属性名')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='建物名')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50, verbose_name='部屋名')),
                ('floor', models.CharField(max_length=50, verbose_name='階')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教授名')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agileca.attribute', verbose_name='属性')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agileca.classroom', verbose_name='教室')),
            ],
            options={
                'unique_together': {('classroom', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='classrooms', through='agileca.ClassroomAttribute', to='agileca.attribute', verbose_name='属性'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='agileca.building', verbose_name='建物'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='agileca.professor', verbose_name='担当教授'),
        ),
    ]
