# Generated by Django 4.2.25 on 2025-12-15 08:00

from django.db import migrations
def add_initial_data(apps, schema_editor):
    Building = apps.get_model('agileca', 'Building')
    Professor = apps.get_model('agileca', 'Professor')
    Attribute = apps.get_model('agileca', 'Attribute')
    Classroom = apps.get_model('agileca', 'Classroom')
    ClassroomAttribute = apps.get_model('agileca', 'ClassroomAttribute')

    # ---------- Building ----------
    b1 = Building.objects.create(name="A")
    b2 = Building.objects.create(name="図書館")
    b3 = Building.objects.create(name="IMC")
    b4 = Building.objects.create(name="B")
    b5 = Building.objects.create(name="F")

    # ---------- Professor ----------
    p1 = Professor.objects.create(name="鈴木")
    p2 = Professor.objects.create(name="後藤")
    p3 = Professor.objects.create(name="Dall'Arno")

    # ---------- Attribute ----------
    a1 = Attribute.objects.create(name="自習")
    a2 = Attribute.objects.create(name="飲食")
    a3 = Attribute.objects.create(name="奨学金")
    a4 = Attribute.objects.create(name="運動")
    # ---------- Classroom ----------
    c1  = Classroom.objects.create(building=b1, room_name="A-101", floor="1", professor=None)
    c2  = Classroom.objects.create(building=b1, room_name="A-105", floor="1", professor=None)
    c3  = Classroom.objects.create(building=b1, room_name="A-106", floor="1", professor=None)
    c4  = Classroom.objects.create(building=b1, room_name="A-108", floor="1", professor=None)
    c5  = Classroom.objects.create(building=b1, room_name="A-109", floor="1", professor=None)
    c6  = Classroom.objects.create(building=b1, room_name="A-110", floor="1", professor=None)
    c7  = Classroom.objects.create(building=b1, room_name="A-111", floor="1", professor=None)
    c8  = Classroom.objects.create(building=b1, room_name="A-114", floor="1", professor=None)

    c9  = Classroom.objects.create(building=b1, room_name="A-201", floor="2", professor=None)
    c10 = Classroom.objects.create(building=b1, room_name="A-202", floor="2", professor=None)
    c11 = Classroom.objects.create(building=b1, room_name="A-203", floor="2", professor=None)
    c12 = Classroom.objects.create(building=b1, room_name="A-205", floor="2", professor=None)
    c13 = Classroom.objects.create(building=b1, room_name="A-206", floor="2", professor=None)
    c14 = Classroom.objects.create(building=b1, room_name="A-207", floor="2", professor=None)
    c15 = Classroom.objects.create(building=b1, room_name="A-208", floor="2", professor=None)
    c16 = Classroom.objects.create(building=b1, room_name="A-209", floor="2", professor=None)

    c17 = Classroom.objects.create(building=b1, room_name="A-301", floor="3", professor=None)
    c18 = Classroom.objects.create(building=b1, room_name="A-302", floor="3", professor=None)
    c19 = Classroom.objects.create(building=b1, room_name="A-303", floor="3", professor=None)
    c20 = Classroom.objects.create(building=b1, room_name="A-304", floor="3", professor=None)
    c21 = Classroom.objects.create(building=b1, room_name="A-306", floor="3", professor=None)
    c22 = Classroom.objects.create(building=b1, room_name="A-307", floor="3", professor=None)
    c23 = Classroom.objects.create(building=b1, room_name="A-308", floor="3", professor=None)
    c24 = Classroom.objects.create(building=b1, room_name="A-309", floor="3", professor=None)
    c25 = Classroom.objects.create(building=b1, room_name="A-311", floor="3", professor=None)
    c26 = Classroom.objects.create(building=b1, room_name="A-312", floor="3", professor=None)

    c27 = Classroom.objects.create(building=b1, room_name="A1-101", floor="1", professor=None)
    c28 = Classroom.objects.create(building=b1, room_name="A1-201", floor="2", professor=None)
    c29 = Classroom.objects.create(building=b1, room_name="A1-301", floor="3", professor=None)

    c30 = Classroom.objects.create(building=b1, room_name="A2-101", floor="1", professor=None)
    c31 = Classroom.objects.create(building=b1, room_name="A2-201", floor="2", professor=None)
    c32 = Classroom.objects.create(building=b1, room_name="A2-301", floor="3", professor=None)



    # ---------- ClassroomAttribute（中間テーブル） ----------

def remove_initial_data(apps, schema_editor):
    Building = apps.get_model('agileca', 'Building')
    Professor = apps.get_model('agileca', 'Professor')
    Attribute = apps.get_model('agileca', 'Attribute')
    Classroom = apps.get_model('agileca', 'Classroom')
    ClassroomAttribute = apps.get_model('agileca', 'ClassroomAttribute')

    # 中間テーブル削除
    ClassroomAttribute.objects.all().delete()

    # 教室削除
    Classroom.objects.all().delete()

    # 属性削除
    Attribute.objects.all().delete()

    # 教授削除（鈴木先生のみ）
    Professor.objects.all().delete()

    # 建物削除
    Building.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0003_seed_classroooms_sql'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, remove_initial_data),
    ]
