# Generated by Antigravity

from django.db import migrations

def cleanup_duplicates(apps, schema_editor):
    Building = apps.get_model('agileca', 'Building')
    Professor = apps.get_model('agileca', 'Professor')
    Attribute = apps.get_model('agileca', 'Attribute')
    Classroom = apps.get_model('agileca', 'Classroom')

    # 1. Building Cleanup
    for name in Building.objects.values_list('name', flat=True).distinct():
        buildings = list(Building.objects.filter(name=name).order_by('id'))
        if len(buildings) > 1:
            original = buildings[0]
            duplicates = buildings[1:]
            for dup in duplicates:
                # Reassign classrooms linked to the duplicate building to the original
                Classroom.objects.filter(building=dup).update(building=original)
                # Delete the duplicate building
                dup.delete()

    # 2. Professor Cleanup
    for name in Professor.objects.values_list('name', flat=True).distinct():
        professors = list(Professor.objects.filter(name=name).order_by('id'))
        if len(professors) > 1:
            original = professors[0]
            duplicates = professors[1:]
            for dup in duplicates:
                # Reassign classrooms (though likely None)
                Classroom.objects.filter(professor=dup).update(professor=original)
                dup.delete()

    # 3. Attribute Cleanup
    for name in Attribute.objects.values_list('name', flat=True).distinct():
        attributes = list(Attribute.objects.filter(name=name).order_by('id'))
        if len(attributes) > 1:
            duplicates = attributes[1:]
            for dup in duplicates:
                # Note: Migration 0004 did not use attributes, so simple deletion is safe
                # If they were used, we'd need to handle M2M through ClassroomAttribute
                dup.delete()

    # 4. Classroom Cleanup
    # After building reassignment, we may have duplicates of (building, room_name)
    # We want to keep the one with the lowest ID (from 0003)
    
    # Get all classrooms ordered by ID
    all_classrooms = Classroom.objects.all().order_by('id')
    seen = set()
    
    for c in all_classrooms:
        key = (c.building_id, c.room_name)
        if key in seen:
            # Duplicate
            c.delete()
        else:
            seen.add(key)

class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0004_seed_classroom_sql'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicates, migrations.RunPython.noop),
    ]
