# Generated by Antigravity

from django.db import migrations

def assign_attributes(apps, schema_editor):
    Classroom = apps.get_model('agileca', 'Classroom')
    Attribute = apps.get_model('agileca', 'Attribute')

    # Ensure attributes exist
    attr_study, _ = Attribute.objects.get_or_create(name="自習")
    attr_eat, _ = Attribute.objects.get_or_create(name="飲食")

    # Classrooms created in 0003_seed_classroooms_sql.py to exclude
    excluded_room_names = [
        "A-101",
        "図書館1階",
        "IMC1階",
        "教務課",
        "F-503"
    ]

    # Iterate over classrooms, excluding the ones from 0003
    # We exclude by room_name. 
    # Note: Migration 0005 cleaned up duplicates, so room_name should be unique per building,
    # but simplest is to exclude by room_name if they are unique enough or use (building, room) if needed.
    # The 0003 classrooms have distinct names from 0004 (which are A-101...A-312 etc).
    # Wait, A-101 is in BOTH 0003 and 0004 lists?
    # 0003: c1 = Classroom.objects.create(building=b1, room_name="A-101", ...)
    # 0004: c1 = Classroom.objects.create(building=b1, room_name="A-101", ...)
    # Migration 0005 deduped them. The user wants to exclude "A-101" from receiving NEW attributes
    # because it likely already has them (or user wants to manually control it).
    
    # We filter OUT the excluded names
    classrooms_to_update = Classroom.objects.exclude(room_name__in=excluded_room_names)

    for classroom in classrooms_to_update:
        classroom.attributes.add(attr_study)
        classroom.attributes.add(attr_eat)

def remove_attributes(apps, schema_editor):
    Classroom = apps.get_model('agileca', 'Classroom')
    Attribute = apps.get_model('agileca', 'Attribute')

    try:
        attr_study = Attribute.objects.get(name="自習")
        attr_eat = Attribute.objects.get(name="飲食")
    except Attribute.DoesNotExist:
        return

    excluded_room_names = [
        "A-101",
        "図書館1階",
        "IMC1階",
        "教務課",
        "F-503"
    ]
    
    classrooms_to_update = Classroom.objects.exclude(room_name__in=excluded_room_names)

    for classroom in classrooms_to_update:
        classroom.attributes.remove(attr_study)
        classroom.attributes.remove(attr_eat)

class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0005_cleanup_duplicates'),
    ]

    operations = [
        migrations.RunPython(assign_attributes, remove_attributes),
    ]
