# Generated by Django 4.2.25 on 2026-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0006_assign_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='size',
            field=models.CharField(blank=True, choices=[('L', '大'), ('M', '中'), ('S', '小')], max_length=1, null=True, verbose_name='サイズ'),
        ),
    ]
