# Generated by Antigravity

from django.db import migrations

def assign_sizes(apps, schema_editor):
    Classroom = apps.get_model('agileca', 'Classroom')
    
    # 1. Update A-101 to Large
    Classroom.objects.filter(room_name="A-101").update(size="L")
    
    # 2. Update A-114 to Medium
    Classroom.objects.filter(room_name="A-114").update(size="M")
    
    # 3. Define excluded classrooms (those that should remain NULL)
    # A-101 and A-114 are also excluded from the "Small" bulk update
    excluded_names = [
        "A-101", 
        "A-114", 
        "図書館1階", 
        "IMC1階", 
        "教務課", 
        "F-503"
    ]
    
    # 4. Update all others to Small
    Classroom.objects.exclude(room_name__in=excluded_names).update(size="S")

def reverse_assign_sizes(apps, schema_editor):
    Classroom = apps.get_model('agileca', 'Classroom')
    # Revert all to NULL
    Classroom.objects.all().update(size=None)

class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0007_classroom_size'),
    ]

    operations = [
        migrations.RunPython(assign_sizes, reverse_assign_sizes),
    ]
