# Generated by Django 4.2.25 on 2026-01-19 07:44

from django.db import migrations



def add_attributes(apps, schema_editor):
    Attribute = apps.get_model('agileca', 'Attribute')
    for name in ["教員居室", "研究室"]:
        Attribute.objects.get_or_create(name=name)

def remove_attributes(apps, schema_editor):
    Attribute = apps.get_model('agileca', 'Attribute')
    Attribute.objects.filter(name__in=["教員居室", "研究室"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0008_assign_classroom_sizes'),
    ]

    operations = [
        migrations.RunPython(add_attributes, remove_attributes),
    ]
