# Generated by Django 4.2.25 on 2026-01-19 08:09

from django.db import migrations



def add_lab_data(apps, schema_editor):
    Building = apps.get_model('agileca', 'Building')
    Classroom = apps.get_model('agileca', 'Classroom')
    Attribute = apps.get_model('agileca', 'Attribute')
    Professor = apps.get_model('agileca', 'Professor')

    # Buildings
    b_f1, _ = Building.objects.get_or_create(name='F1')
    b_f = Building.objects.get(name='F')

    # Attributes
    attr_lab = Attribute.objects.get(name='研究室')
    attr_office = Attribute.objects.get(name='教員居室')

    # Professors
    prof_suzuki, _ = Professor.objects.get_or_create(name='鈴木')
    prof_dallarno, _ = Professor.objects.get_or_create(name="Dall'Arno")

    # Data to create
    # (Building, Room Name, Floor, Attribute, Professor)
    data = [
        # F1 - Labs
        (b_f1, '情報セキュリティ研究室（F1-501）', '5', attr_lab, prof_suzuki),
        (b_f1, '情報セキュリティ研究室（F1-502）', '5', attr_lab, prof_suzuki),
        (b_f1, '情報セキュリティ研究室（F1-503）', '5', attr_lab, prof_suzuki),
        (b_f1, '量子情報研究室（F1-303）', '3', attr_lab, prof_dallarno),
        # F - Offices
        (b_f, 'F-513', '5', attr_office, prof_suzuki),
        (b_f, 'F-506', '5', attr_office, prof_dallarno),
    ]

    for building, room_name, floor, attribute, professor in data:
        classroom, created = Classroom.objects.get_or_create(
            room_name=room_name,
            building=building,
            defaults={
                'floor': floor,
                'professor': professor,
            }
        )
        if not created:
            # Update professor if room already exists
            classroom.professor = professor
            classroom.floor = floor # Update floor just in case
            classroom.save()
        
        classroom.attributes.add(attribute)


def remove_lab_data(apps, schema_editor):
    Classroom = apps.get_model('agileca', 'Classroom')
    # Remove created classrooms
    Classroom.objects.filter(room_name__in=[
        'F1-501', 'F1-502', 'F1-503', 'F1-303',
        'F-513', 'F-506'
    ]).delete()
    
    # Optional: Remove F1 building if no other rooms exist? 
    # Leaving it for safety.


class Migration(migrations.Migration):

    dependencies = [
        ('agileca', '0009_seed_new_attributes'),
    ]

    operations = [
        migrations.RunPython(add_lab_data, remove_lab_data),
    ]
