# Generated by Django 4.2.25 on 2025-11-17 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_scim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100, verbose_name='施設名')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='申請者名')),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('end_time', models.DateTimeField(verbose_name='終了日時')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=10, verbose_name='予約状況')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申請日時')),
            ],
        ),
    ]
