# Generated by Django 4.2.25 on 2025-12-15 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_scim', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approver_comment',
            field=models.TextField(blank=True, null=True, verbose_name='承認者コメント'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='signer_name',
            field=models.CharField(default='', max_length=100, verbose_name='責任者（署名者）'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_signature', '署名待ち'), ('pending_approval', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], default='pending_signature', max_length=20, verbose_name='予約状況'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('applicant', '申請者'), ('signer', '署名者'), ('approver', '承認者')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_scim.reservation')),
            ],
        ),
    ]
