# Generated by Django 4.2.25 on 2025-12-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_kitajaki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255)),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('taste_score', models.IntegerField()),
                ('volume_score', models.IntegerField()),
            ],
        ),
    ]
