# Generated by Django 4.2.25 on 2025-12-17 14:39

from django.db import migrations, models
import django.db.models.deletion
import takenoko.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(verbose_name='値段')),
                ('description', models.TextField(blank=True, verbose_name='説明文')),
                ('condition', models.CharField(choices=[('new', '新品・未使用'), ('good', '目立った傷なし'), ('bad', '傷や汚れあり')], default='good', max_length=10, verbose_name='状態')),
                ('status', models.CharField(choices=[('active', '出品中'), ('negotiation', '交渉中'), ('sold', '売り切れ')], default='active', max_length=20, verbose_name='取引状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='出品日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='成約日時')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='タグ名')),
                ('display_name', models.CharField(max_length=100, verbose_name='表示名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='TakenokoUser',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ユーザーID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=128, verbose_name='パスワードハッシュ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=takenoko.models.avatar_upload_path, verbose_name='ユーザーアイコン')),
                ('nickname', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('student_id', models.CharField(default='unknown', max_length=20, unique=True, verbose_name='学籍番号')),
                ('major', models.CharField(choices=[('1st', '機械工学系'), ('2nd', '電気・電子情報工学系'), ('3rd', '情報・知能工学系'), ('4th', '応用化学・生命工学系'), ('5th', '建築都市システム学系'), ('other', '未配属・その他')], default='other', max_length=50, verbose_name='専攻')),
                ('grade', models.CharField(choices=[('b1', '学部1年'), ('b2', '学部2年'), ('b3', '学部3年'), ('b4', '学部4年'), ('m1', '修士1年'), ('m2', '修士2年'), ('d', '博士課程'), ('other', 'その他')], default='b1', max_length=10, verbose_name='学年')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Takenoko User',
                'verbose_name_plural': 'Takenoko Users',
                'db_table': 'takenoko_users',
            },
        ),
        migrations.CreateModel(
            name='TargetGrade',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='学年コード')),
                ('display_name', models.CharField(max_length=100, verbose_name='表示名')),
            ],
            options={
                'verbose_name': '対象学年',
                'verbose_name_plural': '対象学年',
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=takenoko.models.item_image_upload_path, verbose_name='画像')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='画像順序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='takenoko.item', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品画像',
                'verbose_name_plural': '商品画像',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_items', to='takenoko.takenokouser', verbose_name='購入者'),
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='takenoko.takenokouser', verbose_name='出品者'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='takenoko.tag', verbose_name='タグ/カテゴリ'),
        ),
        migrations.AddField(
            model_name='item',
            name='target_grades',
            field=models.ManyToManyField(blank=True, related_name='items', to='takenoko.targetgrade', verbose_name='対象学年'),
        ),
    ]
