# Generated by Django 4.2.25 on 2025-12-17 06:56

from django.db import migrations, models
import takenoko.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('takenoko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenokouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=takenoko.models.avatar_upload_path, verbose_name='ユーザーアイコン'),
        ),
        migrations.AlterField(
            model_name='takenokouser',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ユーザーID'),
        ),
    ]
