# Generated by Django 4.2.25 on 2026-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takenoko', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', '新品・未使用'), ('like_new', '未使用に近い'), ('good', '目立った傷なし'), ('fair', 'やや傷や汚れあり'), ('bad', '傷や汚れあり')], default='good', max_length=10, verbose_name='状態'),
        ),
    ]
