# Generated by Django 4.2.25 on 2025-11-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
