# Generated by Django 4.2.25 on 2025-11-17 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0002_doko_place_rename_first_name_member_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doko',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place_name',
        ),
        migrations.AddField(
            model_name='member',
            name='current_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mori_doragon_yuhi_machi.place', verbose_name='現在の居場所'),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='田中あ', max_length=100, unique=True, verbose_name='場所の名前'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, verbose_name='メンバー名'),
        ),
    ]
