# Generated by Django 4.2.25 on 2025-11-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0003_delete_doko_remove_place_place_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, verbose_name='場所の名前'),
        ),
    ]
