# Generated by Django 4.2.25 on 2025-11-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0004_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
