# Generated by Django 4.2.25 on 2025-12-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0005_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='場所の名前'),
        ),
    ]
