# Generated by Django 4.2.25 on 2025-12-15 07:53

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0007_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/images/', location=pathlib.PureWindowsPath('C:/Users/tsuboi24/Documents/pbl-app-2025/mori_doragon_yuhi_machi/static/images')), upload_to='', verbose_name='顔写真'),
        ),
    ]
