# Generated by Django 4.2.25 on 2026-01-05 06:37

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0008_alter_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/static/images/', location=pathlib.PureWindowsPath('C:/Users/nomachi24/Documents/pbl-app-2025/pbl-app-2025/mori_doragon_yuhi_machi/static/images')), upload_to='', verbose_name='顔写真'),
        ),
    ]
