# Generated by Django 4.2.25 on 2026-01-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0009_member_updated_at_alter_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Dr', 'Dr'), ('M2', 'M2'), ('M1', 'M1'), ('B4', 'B4'), ('Other', 'Other')], default='Other', max_length=10, verbose_name='学年'),
        ),
    ]
