# Generated by Django 4.2.25 on 2026-01-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori_doragon_yuhi_machi', '0010_member_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('Laboratory', '研究室'), ('LectureRoom', '講義室'), ('Outdoor', '屋外'), ('Home', '自宅'), ('Other', 'その他')], default='Other', max_length=20, verbose_name='場所の種類'),
        ),
    ]
