# Generated by Django 4.2.25 on 2025-11-10 08:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team_cake', '0002_good_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
