# Generated by Django 4.2.25 on 2025-12-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_cake', '0004_good_description_good_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='image',
        ),
        migrations.AddField(
            model_name='good',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
