# Generated by Django 4.2.25 on 2026-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_cake', '0005_remove_good_image_good_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='original_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
