# Generated by Django 4.2.25 on 2026-01-19 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team_cake', '0006_good_original_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='助けてメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='表示中')),
            ],
        ),
    ]
