# Generated by Django 4.2.25 on 2026-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_cake', '0007_sosmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='賞味期限(廃棄予定時刻)'),
        ),
    ]
