# Generated by Django 4.2.25 on 2025-11-17 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100, verbose_name='科目名')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('review', models.TextField(max_length=200, verbose_name='レビュー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '参考書レビュー',
                'verbose_name_plural': '参考書レビュー',
                'ordering': ['-created_at'],
            },
        ),
    ]
