# Generated by Django 4.2.25 on 2025-11-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='review',
            field=models.TextField(verbose_name='レビュー'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='科目名'),
        ),
    ]
