# Generated by Django 4.2.25 on 2025-11-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_alter_bookreview_review_alter_bookreview_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='著者'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='書籍タイトル'),
        ),
    ]
