# Generated by Django 4.2.25 on 2025-11-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0005_bookreview_author_bookreview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='publication_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='発行日'),
        ),
    ]
