# Generated by Django 4.2.25 on 2025-12-22 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0006_bookreview_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('semester', models.CharField(max_length=50, verbose_name='開講学期')),
                ('is_required', models.BooleanField(default=False, verbose_name='必修フラグ')),
                ('grade', models.CharField(max_length=20, verbose_name='開講年次')),
                ('timetable_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='時間割番号')),
                ('numbering', models.CharField(blank=True, max_length=50, null=True, verbose_name='ナンバリング')),
            ],
            options={
                'verbose_name': '開講情報',
                'verbose_name_plural': '開講情報',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='学科名')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='科目名')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='教員名')),
            ],
            options={
                'verbose_name': '教員',
                'verbose_name_plural': '教員',
            },
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='isbn',
            field=models.CharField(max_length=50, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='科目名'),
        ),
        migrations.CreateModel(
            name='SubjectReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=500, verbose_name='レビュー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.courseoffering', verbose_name='開講情報')),
            ],
            options={
                'verbose_name': '科目レビュー',
                'verbose_name_plural': '科目レビュー',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='departments',
            field=models.ManyToManyField(to='graphics.department', verbose_name='開講学科'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.subject', verbose_name='科目'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='teachers',
            field=models.ManyToManyField(to='graphics.teacher', verbose_name='担当教員'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graphics.courseoffering', verbose_name='開講情報'),
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('subject', 'year', 'semester', 'grade')},
        ),
    ]
