# Generated by Django 4.2.27 on 2026-01-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0006_bookreview_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='isbn',
            field=models.CharField(max_length=50, verbose_name='ISBN'),
        ),
    ]
