# Generated by Django 4.2.25 on 2025-12-23 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0007_courseoffering_department_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together=set(),
        ),
    ]
