# Generated by Django 4.2.25 on 2026-01-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0008_alter_courseoffering_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='おすすめ度（0-5）'),
        ),
        migrations.AddField(
            model_name='subjectreview',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='おすすめ度（0-5）'),
        ),
    ]
