# Generated by Django 4.2.25 on 2026-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0009_bookreview_rating_subjectreview_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='title',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='review',
            field=models.TextField(max_length=500, verbose_name='レビュー'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='科目名'),
        ),
    ]
