# Generated by Django 4.2.25 on 2026-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0010_remove_bookreview_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='著者'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='publication_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='発行日'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='書籍タイトル'),
        ),
    ]
