# Generated by Django 4.2.25 on 2026-01-05 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0011_bookreview_author_bookreview_isbn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsUser',
            fields=[
                ('user_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ユーザーID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=128, verbose_name='パスワードハッシュ')),
                ('nickname', models.CharField(max_length=50, verbose_name='ニックネーム')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphics.graphicsuser', verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='subjectreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphics.graphicsuser', verbose_name='投稿者'),
        ),
    ]
