# Generated by Django 4.2.25 on 2026-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0012_graphicsuser_bookreview_user_subjectreview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphicsuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='メール認証済み'),
        ),
        migrations.AddField(
            model_name='graphicsuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='認証トークン'),
        ),
    ]
