# Generated by Django 4.2.25 on 2026-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0013_graphicsuser_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='cover_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='表紙画像URL'),
        ),
    ]
