# Generated by Django 4.2.25 on 2026-01-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0014_bookreview_cover_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='書籍タイトル')),
                ('author', models.CharField(blank=True, max_length=200, null=True, verbose_name='著者')),
                ('publication_date', models.CharField(blank=True, max_length=20, null=True, verbose_name='発行日')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='表紙画像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '書籍',
                'verbose_name_plural': '書籍',
            },
        ),
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graphics.book', verbose_name='書籍'),
        ),
    ]
