# Generated by Django 4.2.25 on 2025-11-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_TeXTeX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='グループ名')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目名')),
                ('function_slug', models.CharField(max_length=50, unique=True, verbose_name='詳細ページ用スラッグ')),
                ('tex_code', models.TextField(verbose_name='参照用TeXコード')),
                ('guide_content', models.TextField(verbose_name='説明文(HTML/Markdown)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='team_TeXTeX.group', verbose_name='所属グループ')),
            ],
        ),
    ]
