# Generated by Django 4.2.25 on 2025-12-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_TeXTeX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='グループ名')),
                ('group_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='グループID')),
            ],
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_content', models.TextField(verbose_name='説明文(HTML/Markdown)')),
                ('guide_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ガイドID')),
            ],
        ),
        migrations.CreateModel(
            name='Slugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_slug', models.CharField(max_length=50, unique=True, verbose_name='詳細ページ用スラッグ')),
                ('slug_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='スラッグID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ユーザーID')),
                ('user', models.CharField(max_length=100, verbose_name='ユーザー名')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='team_TeXTeX.slugs', verbose_name='スラッグ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='team_TeXTeX.users', verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目名')),
                ('tex_code', models.TextField(verbose_name='参照用TeXコード')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='team_TeXTeX.groups', verbose_name='所属グループ')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='team_TeXTeX.guides', verbose_name='ガイド')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='team_TeXTeX.slugs', verbose_name='スラッグ')),
            ],
        ),
    ]
