# Generated by Django 4.2.25 on 2025-12-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_TeXTeX', '0002_groups_guides_slugs_users_favorites_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_TeXTeX.users', verbose_name='作成者')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('content', models.TextField(blank=True, null=True, verbose_name='テキスト内容')),
                ('is_main', models.BooleanField(default=False, verbose_name='メインファイル')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='team_TeXTeX.project', verbose_name='プロジェクト')),
            ],
        ),
    ]
