# Generated by Django 4.2.25 on 2025-11-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='アイコン')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ユーザID')),
                ('email', models.EmailField(max_length=100, verbose_name='メアド')),
                ('password', models.CharField(max_length=100, verbose_name='パスワード')),
                ('grade_department', models.CharField(max_length=100, verbose_name='学年学科')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.CharField(max_length=100, verbose_name='性別')),
                ('club', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属サークル')),
                ('one_word', models.TextField(blank=True, null=True, verbose_name='一言')),
                ('github_account', models.CharField(blank=True, max_length=100, null=True, verbose_name='githubアカウント')),
                ('hobby', models.CharField(blank=True, max_length=200, null=True, verbose_name='趣味')),
                ('birthplace', models.CharField(blank=True, max_length=100, null=True, verbose_name='出身')),
                ('birth_date', models.DateField(verbose_name='誕生日')),
                ('relationship_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='交際ステータス')),
            ],
        ),
    ]
