# Generated by Django 4.2.25 on 2025-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0002_mypage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='grade_department',
        ),
        migrations.AddField(
            model_name='mypage',
            name='department',
            field=models.CharField(choices=[('1系', '1系'), ('2系', '2系'), ('3系', '3系'), ('4系', '4系'), ('5系', '5系')], default='3系', max_length=50, verbose_name='学年'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mypage',
            name='grade',
            field=models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('M1', 'M1'), ('M2', 'M2')], default='M1', max_length=50, verbose_name='学科'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mypage',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他'), ('回答しない', '回答しない')], default='回答しない', max_length=50, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('未婚', '未婚'), ('既婚', '既婚'), ('恋人あり', '恋人あり'), ('募集中', '募集中'), ('秘密', '秘密')], max_length=50, null=True, verbose_name='交際ステータス'),
        ),
    ]
