# Generated by Django 4.2.25 on 2025-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0003_remove_mypage_grade_department_mypage_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='department',
            field=models.CharField(choices=[('1系', '1系'), ('2系', '2系'), ('3系', '3系'), ('4系', '4系'), ('5系', '5系')], max_length=50, null=True, verbose_name='学科'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='grade',
            field=models.CharField(choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('M1', 'M1'), ('M2', 'M2')], max_length=50, null=True, verbose_name='学年'),
        ),
    ]
