# Generated by Django 4.2.25 on 2025-12-15 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0004_alter_mypage_age_alter_mypage_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='コミュニティ名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='communities/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('members', models.ManyToManyField(related_name='communities', to='nanakorobiyaoki.mypage', verbose_name='参加メンバー')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='nanakorobiyaoki.mypage', verbose_name='投稿者')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='nanakorobiyaoki.community', verbose_name='コミュニティ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nanakorobiyaoki.mypage', verbose_name='コメント者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nanakorobiyaoki.post', verbose_name='投稿')),
            ],
        ),
    ]
