# Generated by Django 4.2.25 on 2026-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0005_community_post_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypage',
            name='age',
        ),
        migrations.RemoveField(
            model_name='mypage',
            name='relationship_status',
        ),
        migrations.AlterField(
            model_name='mypage',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='mypage',
            name='user_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='学籍番号(数字6桁)'),
        ),
    ]
