# Generated by Django 4.2.25 on 2026-01-19 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0006_remove_mypage_age_remove_mypage_relationship_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前(フルネーム推奨)'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='nanakorobiyaoki.mypage', verbose_name='受信者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='nanakorobiyaoki.mypage', verbose_name='送信者')),
            ],
        ),
    ]
