# Generated by Django 4.2.25 on 2026-01-19 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0007_alter_mypage_name_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='最終閲覧日時')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='nanakorobiyaoki.community', verbose_name='コミュニティ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_read_statuses', to='nanakorobiyaoki.mypage', verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'コミュニティ既読状態',
                'verbose_name_plural': 'コミュニティ既読状態',
                'unique_together': {('user', 'community')},
            },
        ),
    ]
