# Generated by Django 4.2.25 on 2026-01-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanakorobiyaoki', '0008_communityreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('授業', '授業'), ('サークル', 'サークル'), ('その他', 'その他')], default='その他', max_length=50, verbose_name='カテゴリ'),
        ),
    ]
