# Generated by Django 4.2.25 on 2025-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssk', '0002_post_tag_delete_member_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='イベント日時'),
        ),
    ]
