# Generated by Django 4.2.25 on 2025-12-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssk', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='イベント日'),
        ),
    ]
