# Generated by Django 4.2.25 on 2025-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssk', '0004_post_end_time_post_start_time_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='編集パスワード(ハッシュ)'),
        ),
    ]
