# Generated by Django 4.2.25 on 2025-12-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssk', '0005_post_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='start_time',
        ),
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='イベント日（終了）'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='イベント日（開始）'),
        ),
    ]
