# Generated by Django 4.2.25 on 2025-12-08 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team_giryulink", "0001_initial"),
    ]

    operations = []
