# Generated by Django 4.2.25 on 2025-11-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_giryulink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
