# Generated by Django 4.2.25 on 2025-12-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_giryulink", "0002_auto_20251208_1616"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
