# Generated by Django 5.2.9 on 2025-12-08 07:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team_giryulink", "0003_alter_product_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
    ]
