# Generated by Django 4.2.25 on 2025-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_giryulink', '0004_remove_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_giryulink/products/'),
        ),
    ]
