# Generated by Django 4.2.25 on 2026-01-05 06:27

from django.db import migrations, models
import django.db.models.deletion
import team_giryulink.models


class Migration(migrations.Migration):
    dependencies = [
        ("team_giryulink", "0005_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiryulinkUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[team_giryulink.models.validate_tut_email],
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("name", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="team_giryulink.giryulinkuser",
            ),
        ),
    ]
