# Generated by Django 4.2.25 on 2026-01-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("team_giryulink", "0006_giryulinkuser_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_products",
                to="team_giryulink.giryulinkuser",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purchased_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
