# Generated by Django 4.2.25 on 2026-01-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team_giryulink", "0009_productcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="buyer_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="seller_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
