# Generated by Django 4.2.25 on 2025-11-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
