# Generated by Django 4.2.25 on 2025-11-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='door_comment',
            field=models.TextField(blank=True, help_text='ドアに関する任意コメント'),
        ),
        migrations.AddField(
            model_name='entry',
            name='door_id',
            field=models.CharField(blank=True, help_text='対応したドアID', max_length=64),
        ),
    ]
