# Generated by Django 4.2.25 on 2025-12-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0005_entry_helper_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_code', models.CharField(db_index=True, default='h34vvy', max_length=64)),
                ('local_username', models.CharField(max_length=150)),
                ('user_id', models.PositiveIntegerField(help_text='auth_user.id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['app_code', 'local_username'], name='h34vvy_u53r_app_cod_1a7184_idx')],
                'unique_together': {('app_code', 'local_username')},
            },
        ),
    ]
