# Generated by Django 4.2.25 on 2025-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0006_h34vvygroup_h34vvypermission_h34vvysession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='h34vvyuser',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='アプリ内ポイント'),
        ),
    ]
