# Generated by Django 4.2.25 on 2025-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0006_appaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appaccount',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='アプリ内ポイント'),
        ),
    ]
