# Generated by Django 4.2.25 on 2026-01-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0007_h34vvyuser_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='研究室名', max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='h34vvyuser',
            name='laboratory',
            field=models.ForeignKey(blank=True, help_text='所属研究室', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='h34vvy_users', to='h34vvy_u53rzz.laboratory'),
        ),
    ]
