# Generated by Django 4.2.25 on 2026-01-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0008_laboratory_h34vvyuser_laboratory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h34vvyuser',
            name='laboratory',
            field=models.CharField(blank=True, default='', help_text='所属研究室ID', max_length=50),
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
    ]
