# Generated by Django 4.2.25 on 2025-12-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h34vvy_u53rzz', '0008_h34vvygroup_h34vvypermission_h34vvysession_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppAccount',
            new_name='H34vvyUser',
        ),
        migrations.AlterModelOptions(
            name='h34vvyuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='h34vvyuser',
            table=None,
        ),
    ]
