# Generated by Django 4.2.25 on 2025-11-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
