# Generated by Django 4.2.25 on 2025-11-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0003_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='募集人数 (上限)'),
        ),
        migrations.AddField(
            model_name='post',
            name='recruitment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='募集終了日'),
        ),
        migrations.AddField(
            model_name='post',
            name='recruitment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='募集開始日'),
        ),
    ]
