# Generated by Django 4.2.25 on 2025-11-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0004_post_max_participants_post_recruitment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_participants',
            field=models.PositiveIntegerField(default=0, verbose_name='現在の参加者数'),
        ),
    ]
