# Generated by Django 4.2.25 on 2025-11-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0005_post_current_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='condition_gender',
            field=models.CharField(blank=True, help_text='例: 男性のみ、女性のみ、不問 など', max_length=100, null=True, verbose_name='参加条件：性別'),
        ),
        migrations.AddField(
            model_name='post',
            name='condition_has_disease',
            field=models.CharField(blank=True, help_text='例: なし、呼吸器系の持病がないこと など', max_length=200, null=True, verbose_name='参加条件：持病の有無'),
        ),
        migrations.AddField(
            model_name='post',
            name='condition_nationality',
            field=models.CharField(blank=True, help_text='例: 日本国籍を有する方、不問 など', max_length=100, null=True, verbose_name='参加条件：国籍'),
        ),
    ]
