# Generated by Django 4.2.25 on 2025-11-17 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0006_post_condition_gender_post_condition_has_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='募集人数 (上限)'),
        ),
    ]
