# Generated by Django 4.2.25 on 2025-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0007_alter_post_max_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recruitment_start_date',
        ),
        migrations.AddField(
            model_name='post',
            name='available_slots',
            field=models.JSONField(blank=True, default=list, verbose_name='実験受け入れ可能時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition_gender',
            field=models.CharField(blank=True, choices=[('male', '男性のみ'), ('female', '女性のみ'), ('any', '不問')], max_length=50, null=True, verbose_name='参加条件：性別'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition_has_disease',
            field=models.CharField(blank=True, choices=[('none', 'なし（健康な方）'), ('any', '不問'), ('specific', '特定の持病がないこと（詳細は内容に記述）')], max_length=50, null=True, verbose_name='参加条件：持病'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition_nationality',
            field=models.CharField(blank=True, choices=[('japanese', '日本国籍を有する方'), ('any', '不問'), ('other', 'その他')], max_length=50, null=True, verbose_name='参加条件：国籍'),
        ),
    ]
