# Generated by Django 4.2.25 on 2025-12-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0009_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属（研究室など）'),
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='account',
            name='available_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='参加可能終了時刻'),
        ),
        migrations.AddField(
            model_name='account',
            name='available_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='参加可能開始時刻'),
        ),
        migrations.AddField(
            model_name='account',
            name='desired_max_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='希望する最大所要時間(分)'),
        ),
        migrations.AddField(
            model_name='account',
            name='desired_reward',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='希望する報酬'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, null=True, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='account',
            name='nationality',
            field=models.CharField(blank=True, choices=[('japan', '日本'), ('other', 'その他')], max_length=10, null=True, verbose_name='国籍'),
        ),
    ]
