# Generated by Django 4.2.25 on 2025-12-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0010_account_affiliation_account_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='available_end_time',
        ),
        migrations.RemoveField(
            model_name='account',
            name='available_start_time',
        ),
        migrations.AddField(
            model_name='account',
            name='available_slots',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='参加可能時間帯'),
        ),
    ]
