# Generated by Django 4.2.25 on 2025-12-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0011_remove_account_available_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team_shouronpou.account', verbose_name='投稿者'),
        ),
    ]
