# Generated by Django 4.2.25 on 2025-12-15 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0012_post_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='condition_has_disease',
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(default='', max_length=100, verbose_name='系・所属'),
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.IntegerField(default=0, help_text='分単位で入力', verbose_name='実験所要時間(分)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='free_notes',
            field=models.TextField(blank=True, null=True, verbose_name='その他・自由項目'),
        ),
        migrations.AddField(
            model_name='post',
            name='health_notes',
            field=models.TextField(blank=True, help_text='持病や通院の有無など', null=True, verbose_name='健康面で配慮すべき事項'),
        ),
        migrations.AddField(
            model_name='post',
            name='laboratory',
            field=models.CharField(default='', max_length=100, verbose_name='研究室'),
        ),
        migrations.AddField(
            model_name='post',
            name='reward',
            field=models.CharField(default='', max_length=200, verbose_name='報酬の情報'),
        ),
        migrations.AddField(
            model_name='post',
            name='target_age',
            field=models.CharField(blank=True, help_text='例: 20代, 18歳以上 など', max_length=100, null=True, verbose_name='対象年齢'),
        ),
        migrations.AlterField(
            model_name='post',
            name='available_slots',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='受け入れ可能時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition_gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, null=True, verbose_name='性別条件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition_nationality',
            field=models.CharField(blank=True, choices=[('japan', '日本'), ('other', 'その他')], max_length=10, null=True, verbose_name='国籍条件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='current_participants',
            field=models.IntegerField(default=0, verbose_name='現在の参加者数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='max_participants',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大募集人数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recruitment_end_date',
            field=models.DateField(default='2025-12-31', verbose_name='募集終了日'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='タイトル'),
        ),
    ]
