# Generated by Django 4.2.25 on 2026-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0013_remove_post_condition_has_disease_post_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition_gender',
            field=models.CharField(blank=True, choices=[('unspecified', '指定なし'), ('male', '男性'), ('female', '女性'), ('other', 'その他')], default='unspecified', max_length=15, null=True, verbose_name='性別条件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition_nationality',
            field=models.CharField(blank=True, choices=[('unspecified', '指定なし'), ('japan', '日本'), ('other', 'その他')], default='unspecified', max_length=15, null=True, verbose_name='国籍条件'),
        ),
    ]
