# Generated by Django 4.2.25 on 2026-01-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0014_alter_post_condition_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition_gender',
            field=models.CharField(blank=True, choices=[('unspecified', '指定なし'), ('male', '男性'), ('female', '女性')], default='unspecified', max_length=15, null=True, verbose_name='性別条件'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition_nationality',
            field=models.CharField(blank=True, help_text='例: 日本国籍の方のみ、日本語が流暢な方、など', max_length=100, null=True, verbose_name='国籍条件'),
        ),
    ]
