# Generated by Django 4.2.25 on 2026-01-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0015_alter_post_condition_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition_gender',
            field=models.CharField(choices=[('unspecified', '指定なし'), ('male', '男性'), ('female', '女性')], default='unspecified', max_length=15, verbose_name='性別条件'),
        ),
    ]
