# Generated by Django 4.2.25 on 2026-01-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0016_alter_post_condition_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='desired_reward',
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], default='', max_length=10, verbose_name='性別'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='国籍'),
        ),
    ]
