# Generated by Django 4.2.25 on 2026-01-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_shouronpou', '0017_remove_account_desired_reward_alter_account_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_for_applicants',
            field=models.TextField(blank=True, help_text='応募ボタンが押された後に表示されます。連絡先などを記載してください。', null=True, verbose_name='応募者へのメッセージ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='available_slots',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='空き時間'),
        ),
        migrations.AlterField(
            model_name='account',
            name='desired_max_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='希望最大時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='内容詳細'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='team_shouronpou.account'),
        ),
        migrations.AlterField(
            model_name='post',
            name='department',
            field=models.CharField(max_length=100, verbose_name='系・所属'),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.IntegerField(verbose_name='所要時間(分)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='free_notes',
            field=models.TextField(blank=True, null=True, verbose_name='その他・自由記述'),
        ),
        migrations.AlterField(
            model_name='post',
            name='health_notes',
            field=models.TextField(blank=True, null=True, verbose_name='健康面で配慮すべき事項'),
        ),
        migrations.AlterField(
            model_name='post',
            name='laboratory',
            field=models.CharField(max_length=100, verbose_name='研究室'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reward',
            field=models.CharField(max_length=200, verbose_name='報酬'),
        ),
        migrations.AlterField(
            model_name='post',
            name='target_age',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='対象年齢'),
        ),
    ]
