# Generated by Django 4.2.25 on 2025-12-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='企業名')),
                ('url', models.URLField(blank=True, null=True, verbose_name='企業サイトURL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='紹介文')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='勤務地域')),
                ('avg_annual_income', models.IntegerField(blank=True, null=True, verbose_name='平均年収（万円）')),
                ('starting_salary', models.IntegerField(blank=True, null=True, verbose_name='初任給（万円）')),
                ('annual_holidays', models.IntegerField(blank=True, null=True, verbose_name='年間休日数')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='従業員数')),
                ('internship_acceptance', models.CharField(blank=True, max_length=20, null=True, verbose_name='インターン受け入れ')),
                ('hiring_quota', models.CharField(blank=True, max_length=100, null=True, verbose_name='採用目安')),
                ('selection_process', models.TextField(blank=True, null=True, verbose_name='選考プロセス')),
                ('accepts_jitsumu_kunren', models.BooleanField(default=False, verbose_name='実務訓練受け入れ')),
                ('tut_recommendation', models.BooleanField(default=False, verbose_name='技科大推薦')),
                ('oncampus_briefing', models.CharField(blank=True, max_length=100, null=True, verbose_name='説明会対象分野')),
            ],
            options={
                'verbose_name': '企業',
                'verbose_name_plural': '企業',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学科名')),
                ('short_name', models.CharField(help_text='URLで使う短い名前（例: cs, ee など）', max_length=20, unique=True, verbose_name='URL用スラッグ')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='学籍番号')),
                ('course', models.CharField(choices=[('B', '学部'), ('M', '修士'), ('D', '博士')], max_length=1, verbose_name='課程')),
                ('grade', models.PositiveSmallIntegerField(verbose_name='学年')),
                ('department_name', models.CharField(max_length=50, verbose_name='学科・専攻')),
                ('lab_field', models.CharField(max_length=100, verbose_name='研究分野')),
                ('password', models.CharField(max_length=128, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='学年')),
                ('department_name', models.CharField(blank=True, max_length=50, verbose_name='学科')),
                ('lab_field', models.CharField(blank=True, max_length=100, verbose_name='分野（研究室）')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('no_answer', '回答しない')], max_length=20, verbose_name='性別')),
                ('high_school', models.CharField(blank=True, max_length=100, verbose_name='高校名')),
                ('comment', models.TextField(blank=True, verbose_name='自由記述欄')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評価（★1〜5）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shiokara.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': '企業口コミ',
                'verbose_name_plural': '企業口コミ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.ManyToManyField(related_name='companies', to='shiokara.department', verbose_name='対象学科'),
        ),
    ]
