# Generated by Django 4.2.26 on 2025-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='企業名')),
                ('url', models.URLField(blank=True, verbose_name='企業サイトURL')),
                ('description', models.TextField(blank=True, verbose_name='紹介文')),
            ],
            options={
                'verbose_name': '企業',
                'verbose_name_plural': '企業',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学科名')),
                ('short_name', models.CharField(help_text='URLで使う短い名前（例: cs、ee など）', max_length=20, unique=True, verbose_name='URL用スラッグ')),
            ],
            options={
                'verbose_name': '学科',
                'verbose_name_plural': '学科',
            },
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.ManyToManyField(related_name='companies', to='shiokara.department', verbose_name='対象学科'),
        ),
    ]
