# Generated by Django 4.2.25 on 2025-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='icon_picture',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='アイコン画像'),
        ),
        migrations.AddField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ニックネーム'),
        ),
    ]
