# Generated by Django 4.2.25 on 2025-12-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='seen_tutorial',
            field=models.BooleanField(default=False, verbose_name='チュートリアル表示済み'),
        ),
    ]
