# Generated by Django 4.2.26 on 2025-11-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0002_company_department_delete_member_company_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(help_text='URLで使う短い名前（例: cs, ee など）', max_length=20, unique=True, verbose_name='URL用スラッグ'),
        ),
    ]
