# Generated by Django 4.2.25 on 2025-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0002_person_seen_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='points',
            field=models.IntegerField(default=10, verbose_name='ポイント'),
        ),
    ]
