# Generated by Django 4.2.25 on 2025-12-15 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0002_person_icon_picture_person_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='要望・フィードバック')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='shiokara.person')),
            ],
            options={
                'verbose_name': 'サイト要望',
                'verbose_name_plural': 'サイト要望',
                'ordering': ['-created_at'],
            },
        ),
    ]
