# Generated by Django 4.2.25 on 2025-12-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0003_person_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiokara.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='shiokara.person')),
            ],
            options={
                'verbose_name': '企業閲覧履歴',
                'verbose_name_plural': '企業閲覧履歴',
                'unique_together': {('person', 'company')},
            },
        ),
    ]
