# Generated by Django 4.2.25 on 2025-12-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0003_sitefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='internship_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='インターン締切日'),
        ),
        migrations.AddField(
            model_name='company',
            name='internship_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='インターン開始日'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_year_selection_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='前年度選考開始日'),
        ),
    ]
