# Generated by Django 4.2.25 on 2026-01-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0004_company_internship_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to='shiokara.person', verbose_name='いいねしたユーザー'),
        ),
    ]
