# Generated by Django 4.2.25 on 2025-12-03 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0004_alter_company_description_alter_company_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='学年')),
                ('department_name', models.CharField(blank=True, max_length=50, verbose_name='学科')),
                ('lab_field', models.CharField(blank=True, max_length=100, verbose_name='分野（研究室）')),
                ('gender', models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他'), ('no_answer', '回答しない')], max_length=20, verbose_name='性別')),
                ('high_school', models.CharField(blank=True, max_length=100, verbose_name='高校名')),
                ('comment', models.TextField(blank=True, verbose_name='自由記述欄')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評価（★1〜5）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shiokara.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': '企業口コミ',
                'verbose_name_plural': '企業口コミ',
                'ordering': ['-created_at'],
            },
        ),
    ]
