# Generated by Django 4.2.25 on 2025-12-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0004_companyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='seen_tutorial',
        ),
        migrations.AddField(
            model_name='person',
            name='seen_dept_tutorial',
            field=models.BooleanField(default=False, verbose_name='学科別企業一覧チュートリアル表示済み'),
        ),
        migrations.AddField(
            model_name='person',
            name='seen_points_tutorial',
            field=models.BooleanField(default=False, verbose_name='ポイントチュートリアル表示済み'),
        ),
        migrations.AddField(
            model_name='person',
            name='seen_search_tutorial',
            field=models.BooleanField(default=False, verbose_name='企業検索チュートリアル表示済み'),
        ),
    ]
