# Generated by Django 4.2.25 on 2025-12-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0005_companyreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accepts_jitsumu_kunren',
            field=models.BooleanField(default=False, verbose_name='実務訓練受け入れ'),
        ),
        migrations.AddField(
            model_name='company',
            name='annual_holidays',
            field=models.IntegerField(blank=True, null=True, verbose_name='年間休日数'),
        ),
        migrations.AddField(
            model_name='company',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='勤務地域'),
        ),
        migrations.AddField(
            model_name='company',
            name='avg_annual_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均年収（万円）'),
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='従業員数'),
        ),
        migrations.AddField(
            model_name='company',
            name='hiring_quota',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='採用目安'),
        ),
        migrations.AddField(
            model_name='company',
            name='internship_acceptance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='インターン受け入れ'),
        ),
        migrations.AddField(
            model_name='company',
            name='oncampus_briefing',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='説明会対象分野'),
        ),
        migrations.AddField(
            model_name='company',
            name='selection_process',
            field=models.TextField(blank=True, null=True, verbose_name='選考プロセス'),
        ),
        migrations.AddField(
            model_name='company',
            name='starting_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='初任給（万円）'),
        ),
        migrations.AddField(
            model_name='company',
            name='tut_recommendation',
            field=models.BooleanField(default=False, verbose_name='技科大推薦'),
        ),
    ]
