# Generated by Django 4.2.25 on 2025-12-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0005_remove_person_seen_tutorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreview',
            name='high_school',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, verbose_name='性別'),
        ),
    ]
