# Generated by Django 4.2.25 on 2025-12-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiokara', '0006_remove_companyreview_high_school_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='shiokara.company', verbose_name='お気に入り企業'),
        ),
    ]
