# Generated by Django 4.2.25 on 2025-11-10 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_UD', '0002_event_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
