# Generated by Django 4.2.25 on 2025-11-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_UD', '0003_memo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='memo',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='interview_stage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='memo',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
