# Generated by Django 4.2.25 on 2025-12-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_UD', '0005_account_memo_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='memo',
            name='company_name',
        ),
        migrations.AddField(
            model_name='memo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memos', to='team_UD.company'),
        ),
    ]
