# Generated by Django 4.2.25 on 2025-12-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_UD', '0007_load_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='interview_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='memo',
            name='interview_questions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
