# Generated by Django 4.2.25 on 2025-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team_UD", "0008_memo_interview_details_memo_interview_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
