# Generated by Django 4.2.25 on 2026-01-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_UD', '0009_memo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='status',
        ),
    ]
