# Generated by Django 4.2.25 on 2026-01-19 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_UD', '0010_remove_memo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_UD.account')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team_UD.company')),
                ('related_memo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team_UD.memo')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
