# Generated by Django 4.2.25 on 2026-01-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_UD', '0012_add_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='job_category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
