# Generated by Django 4.2.25 on 2025-11-10 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_akb5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('slow', '遅い'), ('down', 'つながらない')], max_length=10, verbose_name='症状')),
                ('location', models.CharField(choices=[('A', 'A棟'), ('B', 'B棟'), ('C', 'C棟'), ('D', 'D棟')], max_length=1, verbose_name='場所')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='詳細（任意）')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発生時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
            ],
        ),
    ]
