# Generated by Django 4.2.25 on 2025-12-08 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_akb5', '0002_statusreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='発生時刻'),
        ),
    ]
