# Generated by Django 4.2.25 on 2025-12-08 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team_akb5', '0002_statusreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='発生時刻'),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
    ]