# Generated by Django 4.2.25 on 2025-12-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_akb5', '0003_auto_20251208_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='statusreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
