# Generated by Django 4.2.25 on 2025-12-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_akb5', '0004_statusreport_latitude_statusreport_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusreport',
            name='location',
        ),
        migrations.AddField(
            model_name='statusreport',
            name='floor',
            field=models.IntegerField(choices=[(1, '1階'), (2, '2階'), (3, '3階'), (4, '4階'), (5, '5階'), (6, '6階'), (7, '7階'), (8, '8階'), (9, '9階')], default=1, verbose_name='階'),
        ),
    ]
