# Generated by Django 4.2.25 on 2025-10-20 08:21

from django.db import migrations


def add_initial_members(apps, schema_editor):
    """初期メンバーデータを挿入"""
    # モデルを取得
    Member = apps.get_model('team_tansaibou', 'Member')

    # データベースのエイリアスを取得
    db_alias = schema_editor.connection.alias

    # メンバーデータを作成
    members = [
        Member(first_name='純也', last_name='本田'),
        Member(first_name='峻佑', last_name='山北'),
        Member(first_name='圭吾', last_name='小野崎'),
        Member(first_name='光希', last_name='蒔田'),
        Member(first_name='一志', last_name='浦'),
    ]

    # バルクインサートで効率的に挿入
    Member.objects.using(db_alias).bulk_create(members)


class Migration(migrations.Migration):

    dependencies = [
        ('team_tansaibou', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_members),
    ]
