# Generated by Django 4.2.25 on 2025-10-20 08:21

from django.db import migrations


def add_initial_members(apps, schema_editor):
    """初期メンバーデータを挿入"""
    # モデルを取得
    Member = apps.get_model('team_tansaibou', 'Member')

    # データベースのエイリアスを取得
    db_alias = schema_editor.connection.alias

    # メンバーデータを作成
    members = [
        Member(first_name='純也', last_name='本田'),
        Member(first_name='花子', last_name='佐藤'),
        Member(first_name='次郎', last_name='田中'),
    ]

    # バルクインサートで効率的に挿入
    Member.objects.using(db_alias).bulk_create(members)


class Migration(migrations.Migration):

    dependencies = [
        ('team_tansaibou', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_members),
    ]
