# Generated by Django 4.2.25 on 2025-11-10 07:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_tansaibou', '0002_add_initial_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_date', models.DateField(unique=True, verbose_name='集計日')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='売上合計')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='取引件数')),
                ('top_selling_products', models.JSONField(blank=True, default=dict, verbose_name='人気商品データ')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '日次集計',
                'verbose_name_plural': '日次集計',
                'ordering': ['-summary_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('current_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='現在価格')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='在庫数')),
                ('is_set', models.BooleanField(default=False, verbose_name='セット商品')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='販売中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('components', models.ManyToManyField(blank=True, related_name='part_of_sets', to='team_tansaibou.product', verbose_name='セット構成商品')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(verbose_name='販売日時')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='合計金額')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('card', 'カード'), ('electronic', '電子マネー'), ('other', 'その他')], default='cash', max_length=20, verbose_name='支払方法')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team_tansaibou.member', verbose_name='担当者')),
            ],
            options={
                'verbose_name': '販売取引',
                'verbose_name_plural': '販売取引',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
                ('price_at_sale', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='販売時価格')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='小計')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team_tansaibou.product', verbose_name='商品')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='team_tansaibou.transaction', verbose_name='取引')),
            ],
            options={
                'verbose_name': '取引明細',
                'verbose_name_plural': '取引明細',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='変更前価格')),
                ('new_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='変更後価格')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, verbose_name='変更理由')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team_tansaibou.member', verbose_name='変更者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='team_tansaibou.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '価格変更履歴',
                'verbose_name_plural': '価格変更履歴',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-transaction_date'], name='team_tansai_transac_c65f7c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['recorded_by'], name='team_tansai_recorde_6f094e_idx'),
        ),
    ]
