# Generated by Django 4.2.25 on 2025-11-10 08:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_tansaibou', '0003_dailysummary_product_transaction_transactionitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='セット名')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='セット価格')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='販売中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'セット商品',
                'verbose_name_plural': 'セット商品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='数量')),
            ],
            options={
                'verbose_name': 'セット構成商品',
                'verbose_name_plural': 'セット構成商品',
            },
        ),
        migrations.DeleteModel(
            name='DailySummary',
        ),
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_set',
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='team_tansaibou.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='team_tansaibou.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='productsetitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team_tansaibou.product', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='productsetitem',
            name='product_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='team_tansaibou.productset', verbose_name='セット商品'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='product_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='team_tansaibou.productset', verbose_name='セット商品'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='team_tansaibou.productset', verbose_name='セット商品'),
        ),
        migrations.AlterUniqueTogether(
            name='productsetitem',
            unique_together={('product_set', 'product')},
        ),
    ]
