# Generated by Django 4.2.25 on 2025-12-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_tansaibou', '0006_change_member_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '担当者', 'verbose_name_plural': '担当者'},
        ),
    ]
